При помощи библиотеки gspread отправьте данные из предыдущего шага в Google SpreadSheet. Далее отправьте ссылку на получившийся файл в Google SpreadSheet (не забудьте открыть доступ по ссылке, это можно сделать вручную, когда данные уже зальются в таблицу) при помощи VK API себе в личку ВКонтакте.

In [25]:
import gspread
from df2gspread import df2gspread as d2g
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
# Specify path to your file with credentials
path_to_credential = 'test-349116-2684302e4023.json'

# Specify name of table in google sheets
table_name = 'To-do list'
scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name(path_to_credential, scope)
gs = gspread.authorize(credentials)
work_sheet = gs.open(table_name)
# Select 1st sheet
sheet1 = work_sheet.sheet1
# Get data in python lists format
data = sheet1.get_all_values()
# Get header from data
headers = data.pop(0)
# Create df
df = pd.DataFrame(data, columns=headers)
df.head()

  \n To Do                                          2/3 completed
0
1        ✓  Date                                               Task
2     TRUE   7/9    Type anything into column A to complete an item
3    FALSE   8/9  Change the styling of completed items under 'F...
4     TRUE   9/9  Sort items using the drop-down arrows next to ...

In [26]:
table_name = 'A new spreadsheet'
sheet = gs.create(table_name)
my_mail='******.is@gmail.com' # changed to *****
sheet.share(my_mail, perm_type='user', role='writer')
df=pd.read_csv('https://stepik.org/media/attachments/lesson/361618/step_4_lesson_7.csv')
sheet = 'Master'
d2g.upload(df, table_name, sheet, credentials=credentials, row_names=True)

In [31]:
spreadsheet_url = "https://docs.google.com/spreadsheets/d/%s" % sheet.id # получили ссылку на файл в Гугле

In [28]:
table_name = 'A new spreadsheet'
sheet = gs.create(table_name)

In [32]:
spreadsheet_url

'https://docs.google.com/spreadsheets/d/1x9WgMhwYmUcnDdCMNfzbeThvm1viqaUdg_CM12VD55g'

In [34]:
pip install vk_api

Collecting vk_apiNote: you may need to restart the kernel to use updated packages.
  Downloading vk_api-11.9.8-py3-none-any.whl (48 kB)
Requirement already satisfied: requests in c:\users\igor\anaconda3\lib\site-packages (from vk_api) (2.26.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\igor\anaconda3\lib\site-packages (from requests->vk_api) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\igor\anaconda3\lib\site-packages (from requests->vk_api) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\igor\anaconda3\lib\site-packages (from requests->vk_api) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\igor\anaconda3\lib\site-packages (from requests->vk_api) (2.0.4)
Installing collected packages: vk-api
Successfully installed vk-api-11.9.8

In [35]:
import vk_api
# Token which you obtained via vk
app_token = '***********************************************************'# id of the 1st chat changed to ****
chat_id = 1# id of my user-receiver
my_id = ********# Initialize session ... changed to ************
vk_session = vk_api.VkApi(token=app_token)
# Make it possible to use vk api methods as python methods
vk = vk_session.get_api()

In [39]:
import random
vk.messages.send(
chat_id=chat_id,
random_id=random.randint(1, 2 ** 31),
message='https://docs.google.com/spreadsheets/d/1x9WgMhwYmUcnDdCMNfzbeT**************')

4

Другой аналитик уже агрегировал часть данных из метрики. Вам нужно объединить усилия, чтобы получить финальный отчет. Прочитайте дополнительные данные из Google SpreadSheet, объедините вашу таблицу из предыдущего шага с таблицей аналитика и посчитайте количество визитов на человека (отношение visits к users) в разрезе по браузеру и значениям Robots/People.

В ответе укажите, сколько визитов на уникального пользователя совершается ботами с браузера Google Chrome (округлите до целого)

In [40]:
from io import BytesIO
import requests
r = requests.get('https://docs.google.com/spreadsheets/d/e/*********************5hUVmDs497PZOqPYK3exdSikOK/pub?gid=1006633900&single=true&output=csv')
data = r.content

df1 = pd.read_csv(BytesIO(data))

In [49]:
df1.head()

         date         browser user_type  users
0  2020-06-15   Google Chrome    People  240.0
1  2020-06-15   Google Chrome    Robots  104.0
2  2020-06-15  Yandex Browser    People   44.0
3  2020-06-15   Chrome Mobile    People   30.0
4  2020-06-15         Firefox    Robots   29.0

In [48]:
df.head()

         date         browser user_type  visits
0  2020-06-15   Google Chrome    People   250.0
1  2020-06-15   Google Chrome    Robots   104.0
2  2020-06-15  Yandex Browser    People    47.0
3  2020-06-15         Firefox    Robots    31.0
4  2020-06-15   Chrome Mobile    People    31.0

In [51]:
df_merged=df.merge(df1, on=['browser', 'user_type'])

In [52]:
df_merged.head()

       date_x         browser user_type  visits      date_y  users
0  2020-06-15   Google Chrome    People   250.0  2020-06-15  240.0
1  2020-06-15   Google Chrome    Robots   104.0  2020-06-15  104.0
2  2020-06-15  Yandex Browser    People    47.0  2020-06-15   44.0
3  2020-06-15         Firefox    Robots    31.0  2020-06-15   29.0
4  2020-06-15   Chrome Mobile    People    31.0  2020-06-15   30.0

In [54]:
df_merged['ratio_vu']=df_merged.visits/df_merged.users

In [55]:
df_merged

,date_x,browser,user_type,visits,date_y,users,ratio_vu
0,2020-06-15,Google Chrome,People,250.0,2020-06-15,240.0,1.041667
1,2020-06-15,Google Chrome,Robots,104.0,2020-06-15,104.0,1.000000
2,2020-06-15,Yandex Browser,People,47.0,2020-06-15,44.0,1.068182
3,2020-06-15,Firefox,Robots,31.0,2020-06-15,29.0,1.068966
4,2020-06-15,Chrome Mobile,People,31.0,2020-06-15,30.0,1.033333
5,2020-06-15,Firefox,People,27.0,2020-06-15,26.0,1.038462
6,2020-06-15,Safari,Robots,22.0,2020-06-15,20.0,1.100000
7,2020-06-15,Safari,People,19.0,2020-06-15,17.0,1.117647
8,2020-06-15,Mobile Safari,People,15.0,2020-06-15,14.0,1.071429
9,2020-06-15,Opera,People,11.0,2020-06-15,10.0,1.100000
10,2020-06-15,Samsung Internet,People,8.0,2020-06-15,8.0,1.000000
11,2020-06-15,Yandex Browser,Robots,7.0,2020-06-15,7.0,1.000000
12,2020-06-15,Opera,Robots,5.0,2020-06-15,5.0,1.000000
13,2020-06-15,UCWEB,Robots,4.0,2020-06-15,4.0,1.000000
14,2020-06-15,Edge,People,4.0,2020-06-15,4.0,1.000000
15,2020-06-15,Mobile Safari,Robots,1.0,2020-06-15,1.0,1.000000
16,2020-06-15,Android Browser,People,1.0,2020-06-15,1.0,1.000000
17,2020-06-15,Chromium,People,1.0,2020-06-15,1.0,1.000000
18,2020-06-15,Chromium,Robots,1.0,2020-06-15,1.0,1.000000
19,2020-06-15,Yandex: mobile app,People,1.0,2020-06-15,1.0,1.000000
20,2020-06-15,Vivaldi,People,1.0,2020-06-15,1.0,1.000000
21,2020-06-15,Edge,Robots,1.0,2020-06-15,1.0,1.000000
22,2020-06-15,CocCoc,People,1.0,2020-06-15,1.0,1.000000
23,2020-06-15,Samsung Internet,Robots,1.0,2020-06-15,1.0,1.000000